ignore:
  - "**/Mastermind.scala"
  - "**/MastermindModule.scala"
  - "**/model/FileIOComponent/FileIOJsonImpl/FileIO.scala"
  - "**/model/FileIOComponent/FileIOxmlImpl/FileIO.scala"
  - "**/model/FileIOComponent/FileIOyamlImpl/FileIO.scala"